on:
  push:
    branches:
      - master
      - main
      
name: Build & Push

jobs:
  php-fpm:
    name: Build & Deploy to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_REGION: us-east-1

    - name: Action build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: public.ecr.aws/t9f6y4b8
        ECR_REPOSITORY: zizoo/comment-on-pr-cd
        IMAGE_TAG_SHA: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest